### ISSUE TITLE
Creating PyrakoonClient takes 120sec when one node is down

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/pyrakoon#11]
When one node is down in a 3 node cluster the creation of a PyrakoonClient takes 120 sec.
This is not always the case.

To test if the Arakoon was slow or not i ran the arakoon --range-entries on this Arakoon and it returned instantly the keys.

@khenderick you know the details about this issue.

**Comment by wimpers** [comment]
@khenderick can you please update this ticket?

**Comment by JeffreyDevloo** [comment]
There are two connections going out. The default timeout for the nomaster stuff is 60 seconds. Because of those two connections that are being established, the total timeout is amounted to 120s.

I am currently altering this behavior that these timeouts can be overruled with a param.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/pyrakoon/pull/13
The fix for the framework will take a little longer.
